### ISSUE TITLE
Loading json doesn't work

### ISSUE THREAD

**Issue by Erol444** [geaxgx/depthai_pipeline_graph#1]
Hi @geaxgx ,
I have to first say - Awesome tool, thank you so much for making it! One thing off our todo:) I wanted to link this from our debugging docs, but currently loading from json doesn't work.

Here's a simple rgb_preview.py JSON output: https://pastebin.com/zdiBA1Dp
when running `pipeline_graph load pipeline.json` (latest commit of this repo), it just opens the QT window and does nothing.

![image](https://user-images.githubusercontent.com/18037362/179263061-604f3eb9-231e-4dde-beae-84aa8c005276.png)

Running the example with `pipeline_graph run "python3 rgb_preview.py"` works as expected:)
![image](https://user-images.githubusercontent.com/18037362/179263212-72aec11c-c704-4c2d-9b56-c4a67ae397b8.png)

If you could provide some pointers I can also look into it, as I believe it's an extremely useful tool for the whole community!
Thanks again, Erik

**Comment by geaxgx** [comment]
Hi @Erol444 ,
That's because we are talking of 2 different kinds of json files :-)
Currently, the tool can read json files that have been saved from the tool itself (typically when running `pipeline_graph run ...` and then Menu > file > save... or directly Ctrl-S). These json files contains mainly graphical information like position or color of the nodes. So nothing related to the depthai json files you can get with `serializeToJson()`. I remember you asked me on the discord if the tool supported pipeline JSON representation. I replied that currently no, but the tool could be easily modified to support it. It was not clear to me that you wanted the tool to support depthai json files because it seemed to me it was cumbersome for people to modify their code to add a call to `serializeToJson()` then save the json data into a file then call `pipeline_graph load ...` instead of running directly `pipeline_graph run` on their app, so I did not implemented it. I was probably missing the point. I can adapt the tool to support it if you want (end of next week because I am currently on vacation).

**Comment by Erol444** [comment]
Hi @geaxgx ,
I believe that would be very valuable - from top of my head I can think of these usecases:
- When a customer is debugging a pipeline and they just run `DEPTHAI_LEVEL=debug` and we only get the full copied log, together with schema
- Sometimes, it's not possible to run directly, eg. depthai-demo's application, which gets executed as a subprocess

I will create a PR to support this:)

**Comment by Erol444** [comment]
[PR here](https://github.com/geaxgx/depthai_pipeline_graph/pull/2), feel free to link this Issue to it.

**Comment by geaxgx** [comment]
Thank you, I understand now the pertinence of supporting the parsing of the schema from a file.

**Comment by geaxgx** [comment]
( Holydays finished) I updated the repo to include the `from_file` argument to the tool. With this argument, it can now parse a log file containing an execution trace or a Json file created with `serializeToJson()`.

**Comment by geaxgx** [comment]
@Erol444 I am closing this issue. If you decide to include the tool in your own repository in the Luxonis ecosystem, just tell me when it is done and I will update the local README to add a link towards the official Luxonis repo.
